# Generated by Django 2.2.3 on 2019-07-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParamsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='Token')),
                ('owner_id', models.IntegerField(verbose_name='Owner_id')),
                ('group_id', models.IntegerField(verbose_name='Owner_id')),
                ('category_id', models.IntegerField(verbose_name='Category_id')),
                ('version', models.FloatField(verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Param',
                'verbose_name_plural': 'Params',
            },
        ),
    ]
